# Generated by Django 4.2.6 on 2023-11-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('nos', 'Numbers')], default='kg', max_length=3),
        ),
    ]
