# Generated by Django 3.1.13 on 2024-01-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20240103_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delevered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_out_to_delevery',
            field=models.BooleanField(default=False),
        ),
    ]
