# Generated by Django 3.1.13 on 2024-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='town',
            field=models.CharField(choices=[('Mogral', 'Mogral'), ('Mogral Putthur', 'Mogral Putthur'), ('Peral', 'Peral')], default='Mogral', max_length=50),
        ),
    ]
