# Generated by Django 3.1.13 on 2024-01-16 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
    ]
