# Generated by Django 3.1.13 on 2024-01-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
